### PR TITLE
Replay from cursor

### PR DESCRIPTION
**Pull request by bjpbakker**
Support replaying events from a database cursor

### CODE REVIEW

**Comment by lvonk** [comment]
Can you add a spec?

**Comment by lvonk** [comment]
And maybe remove or deprecate the `replay_events`?

**Comment by derekkraan** [comment]
Nice, then we can remove this from Freemle:

https://github.com/zilverline/freemle-sinatra/blob/2dd026e12f380e2ad9a94f4cca6cd0bf836dab44/lib/multi_tenancy.rb#L57

**Comment by bjpbakker** [comment]
Ping @lvonk: thanks, done

**Pull request merged**
